### ISSUE TITLE
Skip links on openredstone.org don't work

### ISSUE THREAD

**Issue by QuickWrite** [OpenRedstoneEngineers/Rules#1]
All of the links that are links to specific elements on the page (with the # symbol) don't work on the https://openredstone.org/rules/ page.

On the GitHub repo it works.

**Comment by QuickWrite** [comment]
It seems to be because the ids for the headers start with `user-content-` which is not in the hyperlinks that the user clicks.

**Comment by Nickster258** [comment]
Thank you for pointing that out. We'll have to see the wordpress plugin this page uses.

**Comment by Nickster258** [comment]
This was solved with some rather admittedly **_jank_** JavaScript on that page.
